project_name: 'secure_ides'

account: '225311078840' #'804450215614'
region: 'us-east-2'

network_definitions:
  vpc_cidr: "192.168.0.0/16"
  max_azs: 2
  nat_gateways: 1
  subnet_configuration:
      -
        name: "public"
        cidr_mask : 24
        subnet_type : "public"
      -
        name: "ides"
        cidr_mask : 24
        subnet_type : "private"

environment_props:
  environment_name: 'DevSecOpsEnvIDE38'
  description: "DevSecOps IDE Blog"
  instance_size: 't3.small'
  automatic_stop_time_minutes: 30
  ebs_volume_size: '16'
  bootstrap_commands: 'bootstrap.sh'

  codecommit_repos:
    - 'SimpleApp'

---
# Tags definitions align with enterprise instructions
tags:
  -
   key: 'Project'
   value: 'SecureIdes'
  -
   key: 'Stack'
   value: 'DevSecOpsEnvIDE38'
  -
   key: 'Environment'
   value: 'Prod'

